#!/bin/bash
set -euox pipefail
shopt -s nullglob

kver=$(ls -1 /usr/lib/modules | tail -n1)

cat >/tmp/fake-uname <<EOF
#!/usr/bin/env bash

if [ "\$1" == "-r" ] ; then
  echo ${kver}
  exit 0
fi

exec /usr/bin/uname \$@
EOF
install -Dm0755 /tmp/fake-uname /tmp/bin/uname

# Workaround for akmod permission issue
chmod 777 /var/tmp
PATH=/tmp/bin:$PATH akmods --force --kernels ${kver}
for ko in /usr/lib/modules/"$kver"/extra/nvidia/*.ko* \
          /usr/lib/modules/"$kver"/extra/v4l2loopback/*.ko*; do
    [[ -f $ko ]] || continue
    if [[ $ko == *.xz ]]; then
        xz -d "$ko"
        ko="${ko%.xz}"
    fi

    /usr/src/kernels/"$kver"/scripts/sign-file sha256 \
        /run/secrets/nuclear.key /etc/pki/akmods/certs/nuclear.crt "$ko"
    xz -f "$ko"
done

chmod 755 /var/tmp
