#!/usr/bin/env bash

set -euo pipefail

systemctl mask bootc-fetch-apply-updates.timer
systemctl enable bootloader-update.service
systemctl enable nix-daemon.service
systemctl disable rpm-ostree-countme.service 
systemctl disable rpm-ostree-countme.timer
