#!/usr/bin/env bash

set -eux pipefail

git clone https://github.com/ashbork/kde /tmp/kde
mv /tmp/kde/Rose\ Pine\ Moon/colorschemes/rose-pine-moon.colors /usr/share/color-schemes
mv /tmp/kde/rose-moon /usr/share/plasma/desktoptheme/rose-moon

git clone https://github.com/vinceliuice/Tela-icon-theme /tmp/Tela-icon-theme
cd /tmp/Tela-icon-theme
./install.sh -d /usr/share/icons dracula
rm -rf /tmp/kde /tmp/Tela-circle-icon-theme

sed -i 's/^SHELL=.*/SHELL=\/bin\/zsh/' /etc/default/useradd
