#!/usr/bin/env bash

set -euo pipefail

dnf config-manager addrepo --from-repofile=https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo
dnf config-manager setopt nvidia-container-toolkit.enabled=0
dnf config-manager setopt nvidia-container-toolkit.gpgcheck=1

dnf -y copr enable eyecantcu/supergfxctl
dnf -y copr enable pgaskin/looking-glass-client

grep -vE '^#' /usr/share/nuclear/packages-added-nvidia | xargs dnf -y install --best --allowerasing
